#!/bin/sh /etc/rc.common

START=50
usb_rndis_init()
{
	sn=`/sbin/uci -q get /data/etc/binfo.binfo.sn`                                                                                                                                                
	adb_id=`echo $sn | awk -F"/" '{print $2}'`
	if [ "x$adb_id" == "x" ]; then
		adb_id=0123456789ABCDEF
	fi
	mount -t configfs none /sys/kernel/config
	mkdir /sys/kernel/config/usb_gadget/amlogic
	cd /sys/kernel/config/usb_gadget/amlogic
	echo 0x18D1 > idVendor
	echo 0x4e26 > idProduct
	mkdir strings/0x409
	echo $adb_id > strings/0x409/serialnumber
	echo xiaomi > strings/0x409/manufacturer
	echo lx06 > strings/0x409/product
	mkdir configs/amlogic.1
	mkdir configs/amlogic.1/strings/0x409
	echo rndis > configs/amlogic.1/strings/0x409/configuration
	echo 500 > configs/amlogic.1/MaxPower
	mkdir functions/rndis.rndis
	ln -s functions/rndis.rndis configs/amlogic.1
	cd /
}

usb_adbd_init()
{
	echo "adb" > /sys/kernel/config/usb_gadget/amlogic/configs/amlogic.1/strings/0x409/configuration
	mkdir /sys/kernel/config/usb_gadget/amlogic/functions/ffs.adb
	mkdir /dev/usb-ffs
	mkdir /dev/usb-ffs/adb
	mount -t functionfs adb /dev/usb-ffs/adb
	ln -s /sys/kernel/config/usb_gadget/amlogic/functions/ffs.adb /sys/kernel/config/usb_gadget/amlogic/configs/amlogic.1/ffs.adb
	/usr/bin/adbd &
	/usr/bin/usb_monitor &
}

usb_net_ipconfig()
{
	ifconfig usb0 172.16.233.1 netmask 255.255.255.0 up
}

function start_usbgadget(){
	usb_dir=/sys/kernel/config/usb_gadget/amlogic
	if [ ! -d ${usb_dir} ]
	then
		usb_rndis_init
		echo "usb rndis start..."
		usb_adbd_init
		echo "usb abdd start..."
		sleep 2
		echo ff400000.dwc2_a > /sys/kernel/config/usb_gadget/amlogic/UDC
		usb_net_ipconfig
		echo "------------------------------------"
		echo "usb rndis & adb start: OK!"
		echo "------------------------------------"
	fi
}

start(){
	channel=`/sbin/uci -q get /usr/share/mico/version.version.CHANNEL`
	if [ "$channel" = "release" ]; then
		return 0
	fi
	start_usbgadget &
}

