#!/bin/sh /etc/rc.common

#start when mesh enabled
#START=81
USE_PROCD=1

MIOT_DID="$(micocfg_miot_did)"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/mdnsd
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    procd_open_instance
    procd_set_param command /usr/bin/central_lite -d "$MIOT_DID" -p /data/
    procd_set_param respawn 3600 5 0
    procd_close_instance
}
