#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1
DEBUG=0

start_service() {

    procd_open_instance
    procd_set_param command /data/user.sh
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 0
    procd_close_instance
}
