#!/bin/sh /etc/rc.common

#START=59

USE_PROCD=1

LOG_TITLE=$0
mico_log() {
    logger -t $LOG_TITLE[$$] -p 3 "$*"
}


start_service() {
  procd_open_instance
  #procd_set_param command udhcpc -f -S -R -t 10 -T 1 -iwlan1
  procd_set_param command udhcpc -f -S -s /bin/simple_dhcp_p2p.sh -R -t 10 -T 1 -iwlan1
  procd_set_param respawn 3600 5 0
  procd_close_instance
}

stop_service() {
  ifconfig wlan1 0.0.0.0
}
