#!/bin/sh /etc/rc.common

#START=59

USE_PROCD=1

UDHCPD_CFG="/tmp/udhcpd.conf"

LOG_TITLE=$0
mico_log() {
    logger -t $LOG_TITLE[$$] -p 3 "$*"
}

config_file_create() {
  local ip="$1"
  echo -e "start $ip.2
end $ip.254
interface wlan1
lease_file      /tmp/udhcpd.leases" > $UDHCPD_CFG
}

start_service() {
  local gw=$(/sbin/route -n | grep 'UG[ \t]' | awk '{print $2}')
  local ip="192.168.1"
  [ x"$ip".1 == x"$gw" ] && {
    ip="192.168.2"
  }
  config_file_create $ip
  ifconfig wlan1 $ip.1 netmask 255.255.255.0
  procd_open_instance
  procd_set_param command udhcpd -f $UDHCPD_CFG
  procd_set_param respawn 3600 5 0
  procd_close_instance
}

stop_service() {
  ifconfig wlan1 0.0.0.0
}
