#!/bin/sh /etc/rc.common

#START=59

USE_PROCD=1

EXTRA_COMMANDS="renew"

LOG_TITLE=$0
mico_log() {
    logger -t $LOG_TITLE[$$] -p 3 "$*"
}

renew() {
  mico_log "renew"
  if pid=$(cat /var/run/udhcpc.pid); then
    kill -SIGUSR1 "$pid"
  else
    restart
  fi
}

start_service() {
  h_name=$(micocfg_dhcp_hostname)
  
  procd_open_instance
  procd_set_param command udhcpc -f -S -s /bin/simple_dhcp.sh -R -t 0 -T 1 -i wlan0 -x "hostname:$h_name"
  procd_set_param respawn 3600 5 0
  procd_set_param pidfile /var/run/udhcpc.pid
  procd_close_instance
}

stop_service() {
  mico_log "rm /tmp/dhcp_done_flag"
  rm "/tmp/dhcp_done_flag" >/dev/null 2>&1
}

restart() {
  
  stop
  start
}
