#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1

config_device_file() {
    mkdir -p /data/dlna/
    cp /usr/share/dlna/device.xml /data/dlna/
    fname=`micocfg_bt_name`
    [ "$fname" == "" ] && {
        fname="小米AI音箱-0001"
    }
    udn=`micocfg_device_id`
    udn="uuid:$udn"
    sed -i "s/\(<friendlyName>\)[^<>]*\(<\/friendlyName\)/\1$fname\2/" /data/dlna/device.xml
    sed -i "s/\(<UDN>\)[^<>]*\(<\/UDN\)/\1$udn\2/" /data/dlna/device.xml
    sync
}

ota_updata_deicie() {
    oldname=`cat /data/dlna/device.xml | grep friendlyName`
    fname=`micocfg_bt_name`
    [ "$fname" == "" ] && {
        fname="小米AI音箱-0001"
    }
    udn=`micocfg_device_id`
    udn="uuid:$udn"
    [ "$oldname" != "<friendlyName>$fname</friendlyName>" ] && {
        sed -i "s/\(<friendlyName>\)[^<>]*\(<\/friendlyName\)/\1$fname\2/" /data/dlna/device.xml
        sed -i "s/\(<UDN>\)[^<>]*\(<\/UDN\)/\1$udn\2/" /data/dlna/device.xml
        sync
    }
}

start_service() {
    dlnaswitch=0
    if [ -f "/data/etc/dlnaswitch.cfg" ];then
        dlnaswitch=`cat /data/etc/dlnaswitch.cfg | grep dlna_status |awk -F "[\"\"]" '{print $2}'`
    fi
    [ x"$dlnaswitch" == x"1" ] && {
	    if [ ! -f "/data/dlna/device.xml" ]; then
		config_device_file
	    fi
	    ota_updata_deicie
	    procd_open_instance
	    procd_set_param command /usr/bin/dlna
	    procd_set_param respawn 3600 5 0
	    procd_close_instance
    }
}

restart()
{
  stop
  start
}
