#!/bin/sh /etc/rc.common

START=79

USE_PROCD=1

start_service() {

  [ x"bluetooth" == x`micocfg_work_mode` ] && {
        logger -t idmruntime.init.d -p 3  "in bluetooth mode, will not start"
        return
  }

  procd_open_instance
  procd_set_param command /usr/bin/idmruntime
  procd_set_param respawn 3600 5 0
  procd_close_instance
}