#!/bin/sh /etc/rc.common

START=70

USE_PROCD=1

start_service() {

  [ x"bluetooth" == x`micocfg_work_mode` ] && {
        logger -t messagingagent.init.d -p 3  "in bluetooth mode, will not start"
        return
  }

  procd_open_instance
  procd_set_param command /usr/bin/messagingagent --handler_threads 8
  procd_set_param respawn 3600 5 0
  procd_set_param stdout 0
  procd_set_param stderr 1
  procd_close_instance
}

stop_service() {
  rm /tmp/messagingagent.lock
}
