#!/bin/sh /etc/rc.common
USE_PROCD=1

mico_log()
{
    logger -t $LOG_TITLE[$$] -p 3 "$*"
}


mesh_proc_choose() {
  PROCNAME="mibt_mesh"
  MESH_PROC="/usr/bin/mibt_mesh"
  WIFI_CHIP=$(micocfg_wifi_chip 2>/dev/null)

  if [[ x"$WIFI_CHIP" = x"8733bs" ]] || [[ x"$WIFI_CHIP" = x"8723ds" ]] || [[  x"$WIFI_CHIP" = x"8821cs" ]]; then
     PROCNAME="mibt_mesh_rtl"
  fi
  
  if [ -f "/data/miio_mpkg/bin/"$PROCNAME ]; then
    MESH_PROC="/data/miio_mpkg/bin/"$PROCNAME
  elif [ -f "/usr/bin/"$PROCNAME ]; then
    MESH_PROC="/usr/bin/"$PROCNAME
  else
    MESH_PROC="/usr/bin/mibt_mesh"
  fi
}

start_service() {
  mesh_proc_choose
  mico_log "mibt_mesh process $MESH_PROC"
  procd_open_instance
  procd_set_param command "$MESH_PROC"
  procd_set_param respawn 3600 5 0   
  procd_set_param pidfile /var/run/mibt_mesh.pid
  procd_close_instance
}
