#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1
DEBUG=0

start_service() {

    [ x"bluetooth" == x`micocfg_work_mode` ] && {
        logger -t mico_ai_crontab.init.d -p 3  "in bluetooth mode, will not start"
        return
    }

    procd_open_instance
    procd_set_param command /usr/bin/mico_ai_crontab
    procd_set_param stdout 0
    procd_set_param stderr 0
    procd_set_param respawn 3600 5 0
    procd_close_instance
}
