#!/bin/sh /etc/rc.common

START=62
USE_PROCD=1

LOG_TITLE=$0
mico_log() {
    logger -t $LOG_TITLE[$$] -p 3 "$*"
}

start_service() {
    mico_log "restart miio_agent"
    [ -f /usr/bin/miio_agent ] && {
        procd_open_instance
        procd_set_param command /usr/bin/miio_agent -l 4
        procd_set_param respawn 3600 5 0
        procd_close_instance
    }
}