#!/bin/sh /etc/rc.common

# miplay will start after wifi connected
# START=99

USE_PROCD=1

LOG_TITLE=$0
mico_log()
{
    logger -t $LOG_TITLE[$$] -p 3 "$*"
}

start_service() {
    [ x"yes" != x`micocfg_is_config_done` ] && {
        mico_log "sys not config done, will not start"
        return
    }
    procd_open_instance
    procd_set_param command /usr/bin/mpas
    procd_set_param nice
    procd_append_param nice -10
    procd_set_param respawn 3600 5 0
    procd_close_instance
}

stop_service() {
    ubus call mediaplayer notify_mdplay_status '{"status":0}' > /dev/null 2>&1
    rm -rf /tmp/multiroom.fifo > /dev/null 2>&1
}

service_started() {
    #renice -n-5 -p
    true
}
