#!/bin/sh /etc/rc.common

#START=59

USE_PROCD=1

LOG_TITLE=$0
mico_log() {
  logger -t $LOG_TITLE[$$] -p 3 "$*"
}


start_service() {
  h_name=$(micocfg_dhcp_hostname)

  procd_open_instance
  procd_set_param command odhcp6c -s /bin/odhcp6c-script.sh -P0 -e -v wlan0
  procd_set_param respawn 3600 5 0
  procd_close_instance
}

# stop_service() {
#   mico_log "rm /tmp/dhcp_done_flag"
#   rm "/tmp/dhcp_done_flag" >/dev/null 2>&1
# }
