#!/bin/sh /etc/rc.common

START=41
USE_PROCD=1
DEBUG=0

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/quickplayer
    procd_set_param nice
    procd_append_param nice -20
    procd_set_param stdout 0
    procd_set_param stderr 0
    procd_set_param respawn 3600 5 0
    procd_close_instance
}
