#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

EXTRA_COMMANDS="clear_data"

start_service() {
    mkdir -p /tmp/mico-voip
    mkdir -p /data/voip/

    local country=$(micocfg_country)
    country=${country:-CN}
    if [ "$country" != "CN" ]; then
        logger -t voip.init[$$] -p 3 "countrycode: $country, not start voip"
        return
    fi

    procd_open_instance
    procd_set_param command /usr/bin/voip_service
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 0
    procd_close_instance
}

stop_service() {
    procd_kill "voip"
    killall -9 voip_applite
    killall -9 voip_service
    /usr/bin/voip_helper -e ring_tts_stop 1>/dev/null 2>/dev/null
    export LED_PARENT="voip.init"; /bin/shut_led 13 1>/dev/null 2>/dev/null
    export LED_PARENT="voip.init"; /bin/shut_led 16 1>/dev/null 2>/dev/null
}

clear_data() {
    rm /data/voip -r -f > /dev/null 2>&1; sync
    restart
}
